{% set name = "alphatwirl" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73605f810ef2c7a1d63e672c24033bb2bb0485fe6e6aa0fbaabdc5a9a8b82543

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - atpbar >=1.0.3
    - mantichora >=0.9.5

test:
  imports:
    - alphatwirl

about:
  home: https://github.com/alphatwirl/alphatwirl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A library for summarizing event data'
  description: |
    AlphaTwirl is a Python library that summarizes event data into
    multivariate categorical data as data frames.
  dev_url: https://github.com/alphatwirl/alphatwirl
  doc_url: https://github.com/alphatwirl/alphatwirl#alphatwirl

extra:
  recipe-maintainers:
    - TaiSakuma
