{% set name = "alphatwirl" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ff0d87fa7c11fdf9655d8647b175dd31c5935b673a2b43959163396213062ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - atpbar >=1.0.3
    - mantichora >=0.9.5

test:
  imports:
    - alphatwirl

about:
  home: https://github.com/alphatwirl/alphatwirl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for summarizing event data
  description: |
    AlphaTwirl is a Python library that summarizes event data into
    multivariate categorical data as data frames.
  dev_url: https://github.com/alphatwirl/alphatwirl
  doc_url: https://github.com/alphatwirl/alphatwirl#alphatwirl

extra:
  recipe-maintainers:
    - TaiSakuma
