travis:
  secure:
    BINSTAR_TOKEN: wnsGmoD/Rlt8FAITQjLKTYkCDgmcePCDjOWNdl2VJX9Zwc01rBYvLzx2YDGtfIPecM+nsNE0IwuF6LxUZzHqPNgddbhaHVsfT/nAEgVApxuXi/2ejuF2dxdrpMgvqClPI1DibAxUuH/sTVio/af/xQdUiAMrqSSSWpz1D4nPioX3n+8U4Jb7NRZQbYIl/VO3iQ6o+2DZz79XyaVEfUH+32MRcslK8FhwaQHQBWea3lrVTfKdeCjvu6z5tptIrLkh5HAAPF1TBVhbYdp+p3/TnpoV3b1vqXsxR8f00O8jnaDKZ8FmCzvAr3BkTTnubjoLN7TvxWxO3WB+dNUaVk6RYvz5ziDFVtyo3OdZbV4QWyX/ueQhjIhfnFxCl9pCAOh8csWJdRmJJfTosfyhcrVoh8yxqXQNCVKHyHTyQEEIK1cFnhFaT0P4SD0i8DT+YJwt8JlLVtQaTzKXXc6aPMnmRQVFHEcm92HE88VxSJEFP6UoXrjK/VfF8qFDvzSegP/+8S6Ur5tdZumbVHa9TgmrzS/qnHI3cXvgl3Q635u6Ip9QXYSRk+AsblOlqz+9Lls2GTi9KPC/PAYTstTbV5KwQ7vWctPgHJ+0f3vsh5PsHdZrOPbUGEsL+6rEucLA5sH8B3gxPIvRX1Sl1jHX+M1JF3HZVdhEioza0E6tDkgPtH4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
